INSERT INTO settings (key, value) VALUES
  ('shop_name', 'My Coffee Shop'),
  ('shop_address', ''),
  ('shop_phone', ''),
  ('logo_path', ''),
  ('currency_code', 'ETB'),
  ('currency_symbol', 'Br'),
  ('decimal_places', '2'),
  ('thousand_separator', ','),
  ('decimal_separator', '.'),
  ('pension_employer_default_pct', '11'),
  ('pension_employee_default_pct', '7'),
  ('standard_days_in_month', '30'),
  ('require_complete_hr_before_payroll', 'true'),
  ('business_day_cutoff', '00:00'),
  ('timezone', 'Africa/Addis_Ababa'),
  ('backup_path', './data/backups/');
